class_name MenuKit
## Small building blocks shared by the menu screens (main menu, settings,
## stats, rules, profiles, locale picker): emoji badges, profile avatars,
## the toast pill and short entrance animations.
##
## Everything visual comes from theme variations generated by
## tools/build_theme.gd (`_extra_menus`) — this file only assembles nodes.

## Solid avatar colours, picked by profile id so a player keeps "their"
## colour across screens.
const AVATAR_COLORS: Array[Color] = [
	Palette.GRAPE, Palette.SKY, Palette.PINK, Palette.MINT, Palette.SUNNY, Palette.CORAL,
]
const AVATAR_EDGES: Array[Color] = [
	Palette.GRAPE_DARK, Palette.SKY_DARK, Palette.PINK_DARK,
	Palette.MINT_DARK, Palette.SUNNY_DARK, Palette.CORAL_DARK,
]

## Max width of the centred content column on wide screens.
const COLUMN_MAX_WIDTH: float = 1120.0

## Logical width a screen is laid out at in portrait (see `fit_portrait`).
const PORTRAIT_WIDTH: float = 720.0


## Portrait "zoom". The project stretches a 1280×720 canvas with aspect
## "expand", so a portrait phone gets a canvas ~1280 units *wide* and all
## UI shrinks to roughly half its landscape size. This scales the screen
## root so it is laid out `PORTRAIT_WIDTH` units wide instead — text and
## touch targets end up the same physical size as in landscape. Landscape
## is left untouched (scale 1). Call on _ready and on viewport resize;
## returns the logical size the screen now has.
static func fit_portrait(root: Control) -> Vector2:
	var vp := root.get_viewport_rect().size
	var k := 1.0
	if vp.y > vp.x:
		k = maxf(1.0, vp.x / PORTRAIT_WIDTH)
	root.set_anchors_preset(Control.PRESET_TOP_LEFT)
	root.position = Vector2.ZERO
	root.scale = Vector2(k, k)
	root.size = vp / k
	return root.size


## Round tinted bubble with an emoji in the middle.
## `variation` is one of the Badge* theme variations (BadgeSunny, …).
static func badge(glyph: String, variation: String, diameter: float = 76.0) -> PanelContainer:
	var panel := PanelContainer.new()
	panel.theme_type_variation = variation
	panel.custom_minimum_size = Vector2(diameter, diameter)
	panel.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	panel.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	panel.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var label := Label.new()
	label.theme_type_variation = "BadgeLabel"
	label.text = glyph
	label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	label.add_theme_font_size_override("font_size", int(diameter * 0.5))
	panel.add_child(label)
	return panel


## Coloured circle with the first letter of the player's name.
static func avatar(player_name: String, profile_id: int, diameter: float = 120.0) -> PanelContainer:
	var idx := posmod(profile_id - 1, AVATAR_COLORS.size())
	var style := StyleBoxFlat.new()
	style.bg_color = AVATAR_COLORS[idx]
	style.border_color = AVATAR_EDGES[idx]
	style.border_width_bottom = 6
	style.set_corner_radius_all(int(diameter))
	style.corner_detail = 16
	style.anti_aliasing = true

	var panel := PanelContainer.new()
	panel.add_theme_stylebox_override("panel", style)
	panel.custom_minimum_size = Vector2(diameter, diameter)
	panel.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	panel.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	panel.mouse_filter = Control.MOUSE_FILTER_IGNORE

	var label := Label.new()
	label.theme_type_variation = "AvatarLabel"
	label.text = initial_of(player_name)
	label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	label.add_theme_font_size_override("font_size", int(diameter * 0.5))
	panel.add_child(label)
	return panel


static func initial_of(player_name: String) -> String:
	var trimmed := player_name.strip_edges()
	if trimmed.is_empty():
		return "?"
	return trimmed.substr(0, 1).to_upper()


## Wraps `content` so it sits in a vertical stack with a small emoji badge
## on top — used by menu tiles (icon above label).
static func tile_content(glyph: String, variation: String, text: String,
		badge_size: float = 64.0) -> VBoxContainer:
	var box := VBoxContainer.new()
	box.alignment = BoxContainer.ALIGNMENT_CENTER
	box.add_theme_constant_override("separation", 6)
	box.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	box.add_child(badge(glyph, variation, badge_size))
	var label := Label.new()
	label.text = text
	label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	label.theme_type_variation = "HeadingLabel"
	label.add_theme_font_size_override("font_size", Palette.FONT_BODY)
	label.text_overrun_behavior = TextServer.OVERRUN_TRIM_ELLIPSIS
	box.add_child(label)
	return box


## Staggered "pop in" for a list of controls: fade from transparent while
## scaling up from 90 %. Total time stays under ~400 ms for short lists.
static func stagger_in(nodes: Array, start_delay: float = 0.0, step: float = 0.05) -> void:
	var i := 0
	for n in nodes:
		var c := n as Control
		if c == null or not c.is_inside_tree():
			continue
		c.modulate.a = 0.0
		var delay := start_delay + step * i
		i += 1
		c.get_tree().process_frame.connect(func() -> void:
			if not is_instance_valid(c):
				return
			c.pivot_offset = c.size / 2.0
			c.scale = Vector2(0.9, 0.9)
			var tw := c.create_tween().set_parallel(true)
			tw.tween_property(c, "modulate:a", 1.0, 0.22).set_delay(delay)
			tw.tween_property(c, "scale", Vector2.ONE, 0.3).set_delay(delay) \
				.set_trans(Tween.TRANS_BACK).set_ease(Tween.EASE_OUT)
		, CONNECT_ONE_SHOT)


## Shows `message` in a toast pill (a ToastPanel holding `label`), then
## fades it away.
static func show_toast(panel: Control, label: Label, message: String, hold: float = 1.4) -> void:
	label.text = message
	panel.visible = true
	panel.modulate.a = 0.0
	var tween := panel.create_tween()
	tween.tween_property(panel, "modulate:a", 1.0, 0.18)
	tween.tween_interval(hold)
	tween.tween_property(panel, "modulate:a", 0.0, 0.3)


## Keeps a scroll column readable on wide screens: side margins grow so the
## content never gets wider than `max_width`.
static func fit_column(margin: MarginContainer, viewport_width: float,
		max_width: float = COLUMN_MAX_WIDTH, min_side: float = 32.0) -> void:
	var side := maxf(min_side, (viewport_width - max_width) * 0.5)
	margin.add_theme_constant_override("margin_left", int(side))
	margin.add_theme_constant_override("margin_right", int(side))


## Friendly display name for the active profile (falls back to "Player 1").
static func active_profile_name() -> String:
	var active_id: int = ProfileService.active_id()
	for entry in ProfileService.list():
		if int(entry.get("id", 0)) == active_id:
			var n := String(entry.get("name", "")).strip_edges()
			if n != "":
				return n
	return TranslationServer.translate("COMMON_DEFAULT_PLAYER")
